Repository trace4cats/trace4cats-avro, pull requests merged in 2021-06, with the labels that each got.

#3 Unify build, workflows
  .github/.mergify.yml
  .github/mergify.yml
  .github/workflows/ci.yml
  .github/workflows/release-drafter.yml
  README.md
  build.sbt
  ci-release.sbt
  project/Dependencies.scala
Labels: skip-changelog

#2 Update sbt to 1.5.4
  project/build.properties
Labels: dependency-update

#4 Improve Exporter fibers finalization
  modules/avro-exporter/src/main/scala/io/janstenpickle/trace4cats/avro/AvroSpanExporter.scala
Labels: enhancement
